"""Constantes de domínio — estados do ciclo de vida e eventos (RN/RF)."""

# Status da solicitação
S_PENDENTE_AUTORIZACAO = "PENDENTE_AUTORIZACAO"
S_AUTORIZADA = "AUTORIZADA"
S_REPROVADA_GESTOR = "REPROVADA_GESTOR"
S_APROVADA_OWNER = "APROVADA_OWNER"
S_REPROVADA_OWNER = "REPROVADA_OWNER"
S_CANCELADA = "CANCELADA"

STATUS_SOLICITACAO_ABERTOS = {S_PENDENTE_AUTORIZACAO, S_AUTORIZADA}
STATUS_SOLICITACAO_CANCELAVEL = {S_PENDENTE_AUTORIZACAO, S_AUTORIZADA}

STATUS_SOLICITACAO_LABEL = {
    S_PENDENTE_AUTORIZACAO: "Pendente de autorização do gestor",
    S_AUTORIZADA: "Aguardando aprovação do owner",
    S_REPROVADA_GESTOR: "Reprovada pelo gestor",
    S_APROVADA_OWNER: "Aprovada pelo owner",
    S_REPROVADA_OWNER: "Reprovada pelo owner",
    S_CANCELADA: "Cancelada",
}

# Status do acesso (distinto da aprovação — RN-018/029)
A_AGUARDANDO_EFETIVACAO = "APROVADO_AGUARDANDO_EFETIVACAO"
A_EFETIVADO = "EFETIVADO"
A_ERRO_EFETIVACAO = "ERRO_EFETIVACAO"
A_REVOGADO = "REVOGADO"

STATUS_ACESSO_LABEL = {
    A_AGUARDANDO_EFETIVACAO: "Aprovado · aguardando efetivação",
    A_EFETIVADO: "Efetivado",
    A_ERRO_EFETIVACAO: "Erro na efetivação",
    A_REVOGADO: "Revogado",
}

# Resultado de decisão
R_APROVADA = "APROVADA"
R_REPROVADA = "REPROVADA"

# Execução técnica
OP_CONCESSAO = "CONCESSAO"
OP_REVOGACAO = "REVOGACAO"
E_PENDENTE = "PENDENTE"
E_EFETIVADA = "EFETIVADA"
E_ERRO = "ERRO"

# Tipo de beneficiário
B_NOMINAL = "NOMINAL"
B_GRUPO = "GRUPO"

# Eventos de auditoria
EV_SOLICITACAO_CRIADA = "SOLICITACAO_CRIADA"
EV_AUTORIZADA = "AUTORIZACAO_HIERARQUICA_APROVADA"
EV_REPROVADA_GESTOR = "AUTORIZACAO_HIERARQUICA_REPROVADA"
EV_APROVADA_OWNER = "APROVACAO_OWNER_APROVADA"
EV_REPROVADA_OWNER = "APROVACAO_OWNER_REPROVADA"
EV_CANCELADA = "SOLICITACAO_CANCELADA"
EV_ACESSO_CRIADO = "ACESSO_CRIADO"
EV_EFETIVADO = "ACESSO_EFETIVADO"
EV_ERRO_EFETIVACAO = "ERRO_EFETIVACAO"
EV_REVOGACAO_SOLICITADA = "REVOGACAO_SOLICITADA"
EV_REVOGADO = "ACESSO_REVOGADO"
